name: CI
on: [push]
jobs:
  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and run tests
      run: |
        sudo xcode-select -s /Applications/Xcode_12.app/Contents/Developer
        xcodebuild -workspace .swiftpm/xcode/package.xcworkspace -scheme SwiftUILib -destination 'platform=iOS Simulator,name=iPhone 11' test
